services:
  app:
    build:
      target: app-interactive
      args:
        LANG: "${LANG}"
        TZ:
        UNMINIMIZE: true
        GIT_USER:
        GIT_EMAIL:
        GIT_DEFAULT_BRANCH: master
        GIT_INSTALL_GCM: false
    environment:
      TERM: "${TERM}"
      HOST_USER: "${USER}"
      ZSH_THEME: powerlevel10k/powerlevel10k
    volumes:
      # Source
      - ".:/app"
      # Dependencies
      - "app.composer:/app/vendor"
      # Build files
      - "app.build:/app/build"
      - "app.logs:/app/logs"
      # Vscode server
      - "vscode:/root/.vscode-server"

volumes:
  app.composer:
    driver: local
  app.build:
    driver: local
  app.logs:
    driver: local
  vscode:
    driver: local
