#!/usr/bin/env php
<?php

use WebTheory\Playground\PlaygroundConfig;
use WebTheory\Playground\PlaygroundMaker;

$root = getcwd();

require $_composer_autoload_path ?? "{$root}/vendor/autoload.php";

$maker = new PlaygroundMaker(new PlaygroundConfig);

$maker->make();
